GET http://localhost:8000/api/v1/menus

################################
POST http://localhost:8000/api/v1/menus
content-type: application/json

{
  "name": "Menu 4",
  "numberOfPallets": 4,
  "items": [
    {
      "name": "Milk",
      "itemsPerBag": 1,
      "itemsPerPack": 12
    },
    {
      "name": "Pancake Mix",
      "itemsPerBag": 2,
      "itemsPerPack": 10
    },
    {
      "name": "Fruit Cup",
      "itemsPerBag": 1,
      "itemsPerPack": 18
    },
    {
      "name": "GoGo Yogurt",
      "itemsPerBag": 1,
      "itemsPerPack": 20
    },
    {
      "name": "Granola Bar",
      "itemsPerBag": 1,
      "itemsPerPack": 8
    }
  ]
}

##################################
GET http://localhost:8000/api/v1/menus/6289c8fcf618b5d92e3af824


#############################
PUT http://localhost:8000/api/v1/menus/6289c8fcf618b5d92e3af824
content-type: application/json

{
  "name": "Menu 2: New",
  "numberOfPallets": 6,
  "items": [
    {
      "name": "Milk",
      "itemsPerBag": 1,
      "itemsPerPack": 12
    },
    {
      "name": "Pancake Mix",
      "itemsPerBag": 2,
      "itemsPerPack": 10
    },
    {
      "name": "Fruit Cup",
      "itemsPerBag": 1,
      "itemsPerPack": 18
    },
    {
      "name": "Oatmeal",
      "itemsPerBag":  4,
      "itemsPerPack": 10
    }
  ]
}

############################################
POST http://localhost:8000/api/v1/menus/6289c8fcf618b5d92e3af824/items
content-type: application/json

{
  "name": "TEST 2",
  "itemsPerBag": 3,
  "itemsPerPack": 13
}
