GET http://localhost:8000/api/v1/menus

################################
POST http://localhost:8000/api/v1/menus
content-type: application/json

{
  "name": "Menu 1",
  "numberOfPallets": 4,
  "items": [
    {
      "name": "Milk",
      "itemsPerBag": 1,
      "itemsPerPack": 12
    },
    {
      "name": "Pancake Mix",
      "itemsPerBag": 2,
      "itemsPerPack": 10
    },
    {
      "name": "Fruit Cup",
      "itemsPerBag": 1,
      "itemsPerPack": 18
    },
    {
      "name": "GoGo Yogurt",
      "itemsPerBag": 1,
      "itemsPerPack": 20
    },
    {
      "name": "Granola Bar",
      "itemsPerBag": 1,
      "itemsPerPack": 8
    }
  ]
}

##################################
GET http://localhost:8000/api/v1/menus/62886863a457477e468538c4